// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: smartwatch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_WatchScreen
void ui_WatchScreen_screen_init(void);
lv_obj_t *ui_WatchScreen;
lv_obj_t *ui_Watchface;
lv_obj_t *ui_LittleHand;
lv_obj_t *ui_BigHand;
lv_obj_t *ui_SecondHand;


// SCREEN: ui_TempScreen
void ui_TempScreen_screen_init(void);
lv_obj_t *ui_TempScreen;
lv_obj_t *ui_TempChart;


// SCREEN: ui_AccelerometerScreen
void ui_AccelerometerScreen_screen_init(void);
lv_obj_t *ui_AccelerometerScreen;
lv_obj_t *ui_AccelerometerChart;


// SCREEN: ui_GryoScreen
void ui_GryoScreen_screen_init(void);
lv_obj_t *ui_GryoScreen;
lv_obj_t *ui_GryoChart;


// SCREEN: ui_MagnetometerScreen
void ui_MagnetometerScreen_screen_init(void);
lv_obj_t *ui_MagnetometerScreen;
lv_obj_t *ui_MagnetometerChart;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_WatchScreen_screen_init();
ui_TempScreen_screen_init();
ui_AccelerometerScreen_screen_init();
ui_GryoScreen_screen_init();
ui_MagnetometerScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_WatchScreen);
}
