// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: smartwatch

#include "ui.h"

void ui_CalendarScreen_screen_init(void)
{
ui_CalendarScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_CalendarScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CalendarScreen, lv_color_hex(0x010000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CalendarScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calendar = lv_calendar_create(ui_CalendarScreen);
lv_calendar_header_arrow_create(ui_Calendar);
lv_obj_set_width( ui_Calendar, 320);
lv_obj_set_height( ui_Calendar, 240);
lv_obj_set_align( ui_Calendar, LV_ALIGN_CENTER );

ui_CalendarOverlay = lv_img_create(ui_CalendarScreen);
lv_img_set_src(ui_CalendarOverlay, &ui_img_overlay_png);
lv_obj_set_width( ui_CalendarOverlay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalendarOverlay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CalendarOverlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CalendarOverlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CalendarOverlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
