// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: smartwatch

#include "ui.h"

void ui_GyroScreen_screen_init(void)
{
ui_GyroScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_GyroScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GyroScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GyroScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GyroChart = lv_chart_create(ui_GyroScreen);
lv_obj_set_width( ui_GyroChart, 249);
lv_obj_set_height( ui_GyroChart, 163);
lv_obj_set_x( ui_GyroChart, 22 );
lv_obj_set_y( ui_GyroChart, 2 );
lv_obj_set_align( ui_GyroChart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_GyroChart, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_GyroChart, LV_CHART_AXIS_PRIMARY_Y, -2000, 2000);
lv_chart_set_range( ui_GyroChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
lv_chart_set_axis_tick( ui_GyroChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 1, true, 50);
lv_chart_set_axis_tick( ui_GyroChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_GyroChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);



ui_GyroLabel = lv_label_create(ui_GyroScreen);
lv_obj_set_width( ui_GyroLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GyroLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GyroLabel, 0 );
lv_obj_set_y( ui_GyroLabel, -100 );
lv_obj_set_align( ui_GyroLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_GyroLabel,"Angular rate (dps)");
lv_obj_set_style_text_color(ui_GyroLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GyroLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
