// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: smartwatch

#include "ui.h"

void ui_WatchScreen_screen_init(void)
{
ui_WatchScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WatchScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WatchScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WatchScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Watchface = lv_img_create(ui_WatchScreen);
lv_img_set_src(ui_Watchface, &ui_img_1308839649);
lv_obj_set_width( ui_Watchface, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Watchface, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Watchface, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Watchface, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Watchface, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTest = lv_label_create(ui_WatchScreen);
lv_obj_set_width( ui_LabelTest, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTest, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTest, -1 );
lv_obj_set_y( ui_LabelTest, -140 );
lv_obj_set_align( ui_LabelTest, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTest,"test");
lv_obj_set_style_text_color(ui_LabelTest, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTest, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
